version: '3.9'

services:
  mongo_db: 
    container_name: db_container_undosxtodo
    image: mongo:latest
    restart: always
    volumes: 
      - ./mongo_db:/data/db 
    ports:  
      - 27017:27017
  api:
    container_name: api_container
    build: .
    ports:
      - "3000:3000"
    environment:
      DB_URI: "mongodb://mongo_db:27017/test"
      SECRET_KEY: "secret@123"
      PORT: 3000
    depends_on:
      - mongo_db
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api 
    ports: 
      - "80:80"
    container_name: "nginx"


